import { King, Queen, Bishop, Knight, Rook, Pawn } from "./classes.js"

// description CREATES OBJECTS OF PIECES WITH RESPECTIVE CLASSES

// info Class("pieceNumber", "pieceColor", "pieceTile")

export var kW = new King( 1, "white" )
export var qW = new Queen( 2, "white" )
export var bW1 = new Bishop( 3, "white", "white" )
export var bW2 = new Bishop( 4, "white", "black" )
export var knW1 = new Knight( 5, "white" )
export var knW2 = new Knight( 6, "white" )
export var rW1 = new Rook( 7, "white" )
export var rW2 = new Rook( 8, "white" )
export var pW1 = new Pawn( 9, "white" )
export var pW2 = new Pawn( 10, "white" )
export var pW3 = new Pawn( 11, "white" )
export var pW4 = new Pawn( 12, "white" )
export var pW5 = new Pawn( 13, "white" )
export var pW6 = new Pawn( 14, "white" )
export var pW7 = new Pawn( 15, "white" )
export var pW8 = new Pawn( 16, "white" )

export var kB = new King( 17, "black" )
export var qB = new Queen( 18, "black" )
export var bB1 = new Bishop( 19, "black", "white" )
export var bB2 = new Bishop( 20, "black", "black" )
export var knB1 = new Knight( 21, "black" )
export var knB2 = new Knight( 22, "black" )
export var rB1 = new Rook( 23, "black" )
export var rB2 = new Rook( 24, "black" )
export var pB1 = new Pawn( 25, "black" )
export var pB2 = new Pawn( 26, "black" )
export var pB3 = new Pawn( 27, "black" )
export var pB4 = new Pawn( 28, "black" )
export var pB5 = new Pawn( 29, "black" )
export var pB6 = new Pawn( 30, "black" )
export var pB7 = new Pawn( 31, "black" )
export var pB8 = new Pawn( 32, "black" )