import {King, Queen, Bishop, Knight, Rook, Pawn} from "./classes.js"

// creates objects of every piece
export var kW = new King("white", "king")
export var qW = new Queen("white", "queen")
export var bW1 = new Bishop("white", "bishop")
export var bW2 = new Bishop("white", "bishop")
export var knW1 = new Knight("white", "knight")
export var knW2 = new Knight("white", "knight")
export var rW1 = new Rook("white", "rook")
export var rW2 = new Rook("white", "rook")
export var pW1 = new Pawn("white", "pawn")
export var pW2 = new Pawn("white", "pawn")
export var pW3 = new Pawn("white", "pawn")
export var pW4 = new Pawn("white", "pawn")
export var pW5 = new Pawn("white", "pawn")
export var pW6 = new Pawn("white", "pawn")
export var pW7 = new Pawn("white", "pawn")
export var pW8 = new Pawn("white", "pawn")

export var kB = new King("black", "king")
export var qB = new Queen("black", "queen")
export var bB1 = new Bishop("black", "bishop")
export var bB2 = new Bishop("black", "bishop")
export var knB1 = new Knight("black", "knight")
export var knB2 = new Knight("black", "knight")
export var rB1 = new Rook("black", "rook")
export var rB2 = new Rook("black", "rook")
export var pB1 = new Pawn("black", "pawn")
export var pB2 = new Pawn("black", "pawn")
export var pB3 = new Pawn("black", "pawn")
export var pB4 = new Pawn("black", "pawn")
export var pB5 = new Pawn("black", "pawn")
export var pB6 = new Pawn("black", "pawn")
export var pB7 = new Pawn("black", "pawn")
export var pB8 = new Pawn("black", "pawn")