import {King, Queen, Bishop, Knight, Rook, Pawn} from "./classes.js"

// creates objects of every piece
export var kW = new King("white")
export var qW = new Queen("white")
export var bW1 = new Bishop("white")
export var bW2 = new Bishop("white")
export var knW1 = new Knight("white")
export var knW2 = new Knight("white")
export var rW1 = new Rook("white")
export var rW2 = new Rook("white")
export var pW1 = new Pawn("white")
export var pW2 = new Pawn("white")
export var pW3 = new Pawn("white")
export var pW4 = new Pawn("white")
export var pW5 = new Pawn("white")
export var pW6 = new Pawn("white")
export var pW7 = new Pawn("white")
export var pW8 = new Pawn("white")

export var kB = new King("black")
export var qB = new Queen("black")
export var bB1 = new Bishop("black")
export var bB2 = new Bishop("black")
export var knB1 = new Knight("black")
export var knB2 = new Knight("black")
export var rB1 = new Rook("black")
export var rB2 = new Rook("black")
export var pB1 = new Pawn("black")
export var pB2 = new Pawn("black")
export var pB3 = new Pawn("black")
export var pB4 = new Pawn("black")
export var pB5 = new Pawn("black")
export var pB6 = new Pawn("black")
export var pB7 = new Pawn("black")
export var pB8 = new Pawn("black")